### PR TITLE
Fix inconsistency of punctuation marks

### PR DESCRIPTION
**Pull request by Hakuyume**
The documents are using both of  `、。` style and `，．` style.

### CODE REVIEW

**Comment by Hakuyume** [comment]
I found this PR is related to #40 .

**Comment by fchollet** [comment]
Wouldn't it be preferable to use `。` and `、` everywhere?

**Comment by Hakuyume** [comment]
I think `，．` is better because it is widely used in Japanese academic papers.
( @henry0312 mentioned `，．` is better at https://github.com/fchollet/keras-docs-ja/issues/40#issuecomment-225482463 )

**Review by henry0312 — APPROVED** [review]
LGTM

**Pull request merged**
